<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Your cart | CampusMarket</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet">
    <style>:root{--ink:#142b38;--muted:#60727a;--paper:#f7faf8;--white:#fff;--line:#dce7e3;--teal:#087f78;--teal-dark:#075b59;--coral:#f07c63}*{box-sizing:border-box}body{margin:0;color:var(--ink);background:var(--paper);font-family:"DM Sans",sans-serif}.container{width:min(1000px,calc(100% - 32px));margin:auto}header{padding:18px 0;border-bottom:1px solid var(--line);background:#fff}.nav{display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:10px;font-family:"Space Grotesk",sans-serif;font-size:1.2rem;font-weight:700;text-decoration:none;color:var(--ink)}.mark{display:grid;place-items:center;width:34px;height:34px;border-radius:9px;color:#fff;background:var(--teal)}.back{color:var(--teal);font-size:.85rem;font-weight:700;text-decoration:none}.page{padding:50px 0}.eyebrow{color:var(--teal);font-size:.75rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase}.heading{display:flex;align-items:end;justify-content:space-between;margin-bottom:26px}.heading h1{margin:9px 0 0;font-family:"Space Grotesk",sans-serif;font-size:2.8rem;letter-spacing:-.05em}.layout{display:grid;grid-template-columns:1fr 320px;gap:24px}.items,.summary{padding:22px;border:1px solid var(--line);border-radius:11px;background:#fff}.cart-item{display:grid;grid-template-columns:88px 1fr auto;align-items:center;gap:15px;padding:14px 0;border-bottom:1px solid var(--line)}.cart-item:first-child{padding-top:0}.cart-item:last-child{border-bottom:0}.cart-item img{width:88px;height:78px;object-fit:cover;border-radius:7px;background:#dce7e3}.cart-item h2{margin:0 0 4px;font-family:"Space Grotesk",sans-serif;font-size:1rem}.cart-item p{margin:0;color:var(--muted);font-size:.78rem}.item-price{font-family:"Space Grotesk",sans-serif;font-weight:700;white-space:nowrap}.remove{margin-top:7px;padding:0;border:0;color:var(--coral);background:none;cursor:pointer;font-size:.75rem}.summary h2{margin:0 0 20px;font-family:"Space Grotesk",sans-serif;font-size:1.25rem}.total{display:flex;justify-content:space-between;padding:17px 0;border-top:1px solid var(--line);font-weight:700}.checkout{width:100%;padding:13px;border:0;border-radius:7px;color:#fff;background:var(--teal);cursor:pointer;font-weight:700}.checkout:hover{background:var(--teal-dark)}.clear{width:100%;margin-top:10px;padding:10px;border:1px solid #f0c4bb;border-radius:7px;color:#a94b39;background:#fff6f4;cursor:pointer;font-size:.8rem;font-weight:700}.empty{padding:40px 20px;color:var(--muted);text-align:center}.empty strong{display:block;margin-bottom:8px;color:var(--ink);font-family:"Space Grotesk",sans-serif;font-size:1.2rem}@media(max-width:720px){.page{padding:30px 0}.heading{align-items:start;flex-direction:column}.heading h1{font-size:2.3rem}.layout{grid-template-columns:1fr}.cart-item{grid-template-columns:65px 1fr auto}.cart-item img{width:65px;height:65px}}
    .add-more{display:inline-flex;align-items:center;gap:8px;padding:11px 16px;border-radius:7px;color:#fff;background:var(--teal);font-size:.85rem;font-weight:700;text-decoration:none}.add-more span{font-size:1.35rem;line-height:.7}.add-more:hover{background:var(--teal-dark)}.remove{display:inline-grid;place-items:center;width:24px;height:24px;margin-left:8px;border:1px solid #f0c4bb;border-radius:50%;color:#a94b39;background:#fff6f4;cursor:pointer;font-size:0;line-height:1}.remove:before{content:"−";font-size:1rem;font-weight:700}.remove:hover{color:#fff;background:var(--coral)}
    </style>
</head>
<body><header><nav class="container nav"><a class="brand" href="index.php"><span class="mark">M</span> CampusMarket</a><a class="back" href="index.php#listings">&larr; Continue shopping</a></nav></header><main class="container page"><div class="heading"><div><span class="eyebrow">Saved for checkout</span><h1>Your cart</h1></div></div><div class="layout"><section class="items" id="cart-items"></section><aside class="summary"><h2>Order summary</h2><div class="total"><span>Total</span><strong id="cart-total">KSh 0</strong></div><button class="checkout" id="checkout" type="button">Continue to checkout</button><button class="clear" id="clear-cart" type="button">Clear cart</button></aside></div></main><script>
const addMore=document.createElement('a');addMore.className='add-more';addMore.href='index.php#listings';addMore.setAttribute('aria-label','Add more products to cart');addMore.innerHTML='<span>+</span> Add products';document.querySelector('.heading').appendChild(addMore);
const cartKey='campusmarket-cart';
const itemsEl=document.getElementById('cart-items');
const totalEl=document.getElementById('cart-total');
function getCart(){return JSON.parse(localStorage.getItem(cartKey)||'[]')}
function renderCart(){const cart=getCart();if(!cart.length){itemsEl.innerHTML='<div class="empty"><strong>Your cart is empty</strong>Add a product from the catalog to see it here.</div>';totalEl.textContent='KSh 0';return}let total=0;itemsEl.innerHTML=cart.map(function(item,index){total+=Number(item.price);return '<article class="cart-item"><img src="'+item.image+'" alt="'+item.title+'"><div><h2>'+item.title+'</h2><p>'+item.category+'</p><button class="remove" type="button" data-index="'+index+'">Remove</button></div><strong class="item-price">KSh '+Number(item.price).toLocaleString()+'</strong></article>'}).join('');totalEl.textContent='KSh '+total.toLocaleString();document.querySelectorAll('.remove').forEach(function(button){button.onclick=function(){const next=getCart();next.splice(Number(button.dataset.index),1);localStorage.setItem(cartKey,JSON.stringify(next));renderCart()}})}
document.getElementById('clear-cart').onclick=function(){localStorage.removeItem(cartKey);renderCart()};document.getElementById('checkout').onclick=function(){alert('Checkout will be available after account and payment setup.')};renderCart();
</script></body>
</html>
