<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Browse categories | CampusMarket</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet">
    <style>:root{--ink:#142b38;--muted:#60727a;--paper:#f7faf8;--white:#fff;--line:#dce7e3;--teal:#087f78;--teal-dark:#075b59}*{box-sizing:border-box}body{margin:0;color:var(--ink);background:var(--paper);font-family:"DM Sans",sans-serif}.container{width:min(1000px,calc(100% - 32px));margin:auto}header{padding:18px 0;border-bottom:1px solid var(--line);background:#fff}.nav{display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:10px;color:var(--ink);font-family:"Space Grotesk",sans-serif;font-size:1.2rem;font-weight:700;text-decoration:none}.mark{display:grid;place-items:center;width:34px;height:34px;border-radius:9px;color:#fff;background:var(--teal)}.back{color:var(--teal);font-size:.85rem;font-weight:700;text-decoration:none}.page{padding:60px 0}.eyebrow{color:var(--teal);font-size:.76rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase}.heading h1{margin:12px 0 8px;font-family:"Space Grotesk",sans-serif;font-size:3rem;letter-spacing:-.05em}.heading p{margin:0 0 30px;color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.category{display:block;min-height:170px;padding:22px;border:1px solid var(--line);border-radius:10px;color:var(--ink);background:#fff;text-decoration:none;transition:transform .2s,box-shadow .2s}.category:hover{transform:translateY(-4px);box-shadow:0 18px 45px rgba(20,43,56,.1)}.icon{display:grid;place-items:center;width:46px;height:46px;margin-bottom:34px;border-radius:9px;color:var(--teal-dark);background:#e7f3ee;font-size:1.3rem}.category:nth-child(2) .icon{background:#fff0da}.category:nth-child(3) .icon{background:#ffe3dc}.category:nth-child(4) .icon{background:#e4edf8}.category:nth-child(5) .icon{background:#f0e7f5}.category:nth-child(6) .icon{background:#e7eff8}.category strong{display:block;font-family:"Space Grotesk",sans-serif;font-size:1.1rem}.category span{color:var(--muted);font-size:.8rem}@media(max-width:650px){.page{padding:35px 0}.heading h1{font-size:2.3rem}.grid{grid-template-columns:1fr 1fr}}@media(max-width:420px){.grid{grid-template-columns:1fr}}
    </style>
</head>
<body><header><nav class="container nav"><a class="brand" href="index.php"><span class="mark">M</span> CampusMarket</a><a class="back" href="index.php#browse">&larr; Back to marketplace</a></nav></header><main class="container page"><div class="heading"><span class="eyebrow">Browse the marketplace</span><h1>Find what you need, faster.</h1><p>Choose a category to see available products near campus.</p></div><div class="grid"><a class="category" href="index.php?category=Textbooks#listings"><span class="icon">&#9878;</span><strong>Textbooks</strong><span>Books for every semester</span></a><a class="category" href="index.php?category=Furniture#listings"><span class="icon">&#9733;</span><strong>Furniture</strong><span>Make your space yours</span></a><a class="category" href="index.php?category=Fashion#listings"><span class="icon">&#9829;</span><strong>Fashion</strong><span>Good style, better prices</span></a><a class="category" href="index.php?category=Electronics#listings"><span class="icon">&#9673;</span><strong>Electronics</strong><span>Useful tech for campus life</span></a><a class="category" href="index.php?category=Phones+%26+gadgets#listings"><span class="icon">&#9742;</span><strong>Phones &amp; gadgets</strong><span>Stay connected for less</span></a><a class="category" href="index.php?category=Transport#listings"><span class="icon">&#9736;</span><strong>Transport</strong><span>Bikes and everyday mobility</span></a></div></main></body>
</html>
