<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="CampusMarket is the trusted marketplace for students to buy, sell, and discover more on campus.">
	<title>CampusMarket | Your campus, your marketplace</title>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet">
	<style>
		:root{--ink:#142b38;--muted:#60727a;--paper:#f7faf8;--white:#fff;--line:#dce7e3;--teal:#087f78;--teal-dark:#075b59;--coral:#f07c63;--shadow:0 18px 45px rgba(20,43,56,.1)}
		*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);background:var(--paper);font-family:"DM Sans",sans-serif;line-height:1.5}a{color:inherit;text-decoration:none}button,input{font:inherit}.container{width:min(1160px,calc(100% - 40px));margin:auto}
		.topbar{background:var(--ink);color:#d9e7e3;font-size:.82rem}.topbar .container{display:flex;justify-content:space-between;padding:9px 0}.topbar a{color:#fff;font-weight:700}header{background:var(--white);border-bottom:1px solid var(--line)}.nav{min-height:78px;display:flex;align-items:center;gap:34px}.brand{display:flex;align-items:center;gap:10px;font-family:"Space Grotesk",sans-serif;font-size:1.3rem;font-weight:700;letter-spacing:-.04em;white-space:nowrap}.brand-mark{display:grid;place-items:center;width:34px;height:34px;border-radius:9px;color:#fff;background:var(--teal);font-size:1.1rem}.nav-links{display:flex;gap:25px;margin-right:auto;color:var(--muted);font-size:.92rem;font-weight:600}.nav-links a:hover{color:var(--teal)}.nav-actions{display:flex;align-items:center;gap:15px}.sell-link{color:var(--teal);font-weight:700;font-size:.92rem}.button{display:inline-flex;justify-content:center;align-items:center;gap:8px;border:0;border-radius:7px;padding:12px 18px;color:#fff;background:var(--teal);cursor:pointer;font-weight:700;transition:transform .2s,background .2s}.button:hover{background:var(--teal-dark);transform:translateY(-2px)}
		.hero{overflow:hidden;padding:74px 0 84px;background:#e8f3ed}.hero-grid{display:grid;grid-template-columns:1fr .92fr;align-items:center;gap:65px}.eyebrow{display:inline-flex;align-items:center;gap:8px;color:var(--teal);font-size:.77rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase}.eyebrow:before{width:24px;height:2px;background:var(--coral);content:""}h1,h2,h3{font-family:"Space Grotesk",sans-serif;line-height:1.08;letter-spacing:-.045em}h1{max-width:590px;margin:18px 0 20px;font-size:clamp(2.75rem,5vw,4.65rem)}.hero-copy{max-width:500px;color:var(--muted);font-size:1.08rem}.search{display:flex;max-width:510px;margin-top:30px;padding:6px;gap:8px;border:1px solid #c8ded5;border-radius:9px;background:#fff;box-shadow:0 8px 24px rgba(20,43,56,.07)}.search input{min-width:0;flex:1;border:0;outline:0;padding:9px 12px;color:var(--ink)}.search input::placeholder{color:#8a999c}.hero-art{position:relative;min-height:370px}.hero-photo{width:86%;height:350px;margin-left:auto;overflow:hidden;border-radius:16px 16px 16px 70px;box-shadow:var(--shadow);transform:rotate(2deg)}.hero-photo img{width:100%;height:100%;object-fit:cover}.float-card{position:absolute;right:0;bottom:18px;display:flex;align-items:center;gap:12px;padding:14px 17px;border-radius:10px;background:#fff;box-shadow:var(--shadow);font-size:.84rem}.avatar-stack{display:flex}.avatar-stack span{display:grid;place-items:center;width:29px;height:29px;margin-left:-7px;border:2px solid #fff;border-radius:50%;color:#fff;background:var(--coral);font-size:.68rem;font-weight:700}.avatar-stack span:first-child{margin-left:0;background:var(--teal)}.float-card strong{display:block;font-family:"Space Grotesk",sans-serif}
		.section{padding:76px 0}.section-heading{display:flex;align-items:end;justify-content:space-between;margin-bottom:26px}.section-heading h2{margin:9px 0 0;font-size:2.15rem}.section-heading a{color:var(--teal);font-size:.9rem;font-weight:700}.category-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.category{position:relative;min-height:165px;overflow:hidden;padding:20px;border-radius:10px;background:#fff;border:1px solid var(--line);transition:transform .2s,box-shadow .2s}.category:hover{transform:translateY(-4px);box-shadow:var(--shadow)}.category:after{position:absolute;right:-18px;bottom:-28px;width:100px;height:100px;border-radius:50%;background:#e7f3ee;content:""}.category:nth-child(2):after{background:#fff0da}.category:nth-child(3):after{background:#ffe3dc}.category:nth-child(4):after{background:#e4edf8}.category-icon{display:grid;place-items:center;width:44px;height:44px;margin-bottom:29px;border-radius:9px;color:var(--teal-dark);background:#e7f3ee;font-size:1.3rem}.category:nth-child(2) .category-icon{background:#fff0da}.category:nth-child(3) .category-icon{background:#ffe3dc}.category:nth-child(4) .category-icon{background:#e4edf8}.category strong{position:relative;z-index:1;display:block;font-family:"Space Grotesk",sans-serif;font-size:1.05rem}.category small{color:var(--muted);font-size:.78rem}
		.listings{background:#fff}.listing-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.listing{overflow:hidden;border:1px solid var(--line);border-radius:10px;background:#fff}.listing-image{position:relative;height:215px;overflow:hidden;background:#d9e6e0}.listing-image img{width:100%;height:100%;object-fit:cover;transition:transform .4s}.listing:hover img{transform:scale(1.04)}.tag{position:absolute;top:13px;left:13px;padding:5px 9px;border-radius:4px;color:var(--teal-dark);background:#e7f3ee;font-size:.7rem;font-weight:700}.listing-body{padding:17px}.listing-body h3{margin:0 0 8px;font-size:1.12rem;letter-spacing:-.025em}.listing-meta{display:flex;justify-content:space-between;color:var(--muted);font-size:.79rem}.price{margin-top:14px;color:var(--ink);font-family:"Space Grotesk",sans-serif;font-size:1.2rem;font-weight:700}.price span{color:var(--muted);font-family:"DM Sans",sans-serif;font-size:.78rem;font-weight:400}
		.trust{padding:54px 0;border-top:1px solid var(--line);background:#f7faf8}.trust-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:35px}.trust-item{display:flex;gap:15px}.trust-item>b{display:grid;place-items:center;flex:0 0 38px;height:38px;border-radius:50%;color:var(--teal-dark);background:#dcefe8}.trust-item strong{display:block;margin-bottom:3px;font-family:"Space Grotesk",sans-serif}.trust-item p{margin:0;color:var(--muted);font-size:.84rem}footer{padding:34px 0;color:#c7d8d5;background:var(--ink)}.footer-row{display:flex;align-items:center;justify-content:space-between;gap:25px}footer .brand{color:#fff}footer small{color:#9eb6b2}.footer-links{display:flex;gap:22px;font-size:.82rem}
		@media(max-width:800px){.container{width:min(100% - 28px,600px)}.topbar .container{display:block;text-align:center}.topbar .container span{display:none}.nav{min-height:68px;gap:15px}.nav-links{display:none}.sell-link{display:none}.hero{padding:55px 0 65px}.hero-grid{grid-template-columns:1fr;gap:38px}h1{font-size:3.1rem}.hero-art{min-height:280px}.hero-photo{height:270px;width:92%}.category-grid{grid-template-columns:repeat(2,1fr)}.listing-grid,.trust-grid{grid-template-columns:1fr}.listing-image{height:230px}.section{padding:57px 0}.footer-row{align-items:flex-start;flex-direction:column}}
		@media(max-width:430px){.nav-actions .button{padding:10px 12px;font-size:.82rem}.brand{font-size:1.1rem}h1{font-size:2.65rem}.search{flex-direction:column;border:0;padding:0;background:transparent;box-shadow:none}.search input{min-height:48px;border:1px solid #c8ded5;border-radius:7px}.search .button{min-height:48px}.section-heading{align-items:flex-start;flex-direction:column;gap:10px}}
	</style>
</head>
<body>
	<div class="topbar"><div class="container"><span>Built for students, by students</span><span>New here? <a href="#how-it-works">See how it works</a></span></div></div>
	<header><nav class="container nav" aria-label="Main navigation"><a class="brand" href="index.php"><span class="brand-mark">M</span> CampusMarket</a><div class="nav-links"><a href="#browse">Browse</a><a href="#how-it-works">How it works</a><a href="#about">About us</a></div><div class="nav-actions"><a class="sell-link" href="#sell">Sell an item</a><a class="button" href="#join">Join free</a></div></nav></header>
	<main>
		<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">The student marketplace</span><h1>Make room for what matters next.</h1><p class="hero-copy">Find useful things nearby, give your old gear a second life, and keep more money in your pocket.</p><form class="search" action="#browse" role="search"><input type="search" aria-label="Search listings" placeholder="Search textbooks, bikes, furniture..."><button class="button" type="submit">Search</button></form></div><div class="hero-art" aria-label="Students browsing CampusMarket"><div class="hero-photo"><img src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=85" alt="Students talking together on campus"></div><div class="float-card"><div class="avatar-stack"><span>AJ</span><span>KM</span><span>+</span></div><div><strong>12,000+ students</strong><span>are already buying local</span></div></div></div></div></section>
		<section class="section" id="browse"><div class="container"><div class="section-heading"><div><span class="eyebrow">Explore campus finds</span><h2>What are you looking for?</h2></div><a href="#listings">View all categories &rarr;</a></div><div class="category-grid"><a class="category" href="#listings"><span class="category-icon">&#9878;</span><strong>Textbooks</strong><small>Save on your next semester</small></a><a class="category" href="#listings"><span class="category-icon">&#9733;</span><strong>Room &amp; home</strong><small>Make your space yours</small></a><a class="category" href="#listings"><span class="category-icon">&#9829;</span><strong>Fashion</strong><small>Good style, better prices</small></a><a class="category" href="#listings"><span class="category-icon">&#9673;</span><strong>Tech &amp; bikes</strong><small>Gear up and get moving</small></a></div></div></section>
		<section class="section listings" id="listings"><div class="container"><div class="section-heading"><div><span class="eyebrow">Fresh this week</span><h2>Popular near you</h2></div><a href="#browse">See all listings &rarr;</a></div><div class="listing-grid"><article class="listing"><div class="listing-image"><span class="tag">Like new</span><img src="https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=700&q=80" alt="Stack of university textbooks"></div><div class="listing-body"><h3>Calculus &amp; Physics bundle</h3><div class="listing-meta"><span>Engineering · 0.4 mi</span><span>Today</span></div><div class="price">$45 <span>for 3 books</span></div></div></article><article class="listing"><div class="listing-image"><span class="tag">Pickup today</span><img src="https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=700&q=80" alt="Comfortable green lounge chair"></div><div class="listing-body"><h3>Olive reading chair</h3><div class="listing-meta"><span>Home · 0.8 mi</span><span>Yesterday</span></div><div class="price">$60 <span>negotiable</span></div></div></article><article class="listing"><div class="listing-image"><span class="tag">Verified seller</span><img src="https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=700&q=80" alt="Black bicycle parked outdoors"></div><div class="listing-body"><h3>City commuter bike</h3><div class="listing-meta"><span>Transport · 1.2 mi</span><span>2 days ago</span></div><div class="price">$180 <span>excellent condition</span></div></div></article></div></div></section>
		<section class="trust" id="how-it-works"><div class="container trust-grid"><div class="trust-item"><b>1</b><div><strong>List in a minute</strong><p>Snap a photo, set your price, and reach people on your campus.</p></div></div><div class="trust-item"><b>2</b><div><strong>Meet with confidence</strong><p>Chat safely and choose a public campus pickup spot.</p></div></div><div class="trust-item"><b>3</b><div><strong>Keep it circular</strong><p>Save cash, reduce waste, and pass good things forward.</p></div></div></div></section>
	</main>
	<footer id="about"><div class="container footer-row"><a class="brand" href="index.php"><span class="brand-mark">M</span> CampusMarket</a><div class="footer-links"><a href="#about">About</a><a href="#how-it-works">Safety</a><a href="#about">Contact</a></div><small>&copy; 2026 CampusMarket</small></div></footer>
</body>
</html>
