services:
  - type: web
    name: campusmarket
    runtime: docker
    plan: free
    healthCheckPath: /index.php
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: campusmarket
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: AT_USERNAME
        sync: false
      - key: AT_API_KEY
        sync: false
      - key: AT_SENDER_ID
        sync: false
